dist: trusty

notifications:
  email: false

services:
  - docker

before_script:
  - docker-compose run app bin/wait-for-deps.sh
  - docker-compose run --rm app python manage.py migrate
  - docker-compose run --rm app python manage.py loaddata demodata.json
  - docker-compose up -d

script:
  - coverage run -a --source=pombola,pombola_sayit,wordcloud,writeinpublic ./manage.py test --settings=pombola.settings.tests_south_africa
  - wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 -qO- http://0.0.0.0:8000/position/member/parliament/?order=name&a=1 | grep "Ramokgopa"

after_script:
  # Log output in case issues occurred where this can help us debug quicly
  - docker-compose logs db elasticsearch

  # Run codecov passing appropriate codecov.io CI environment variables to container
  - "docker-compose run --rm `bash <(curl -s https://codecov.io/env)` app codecov"
